### ISSUE TITLE
Missing argument in the sprintf-function

### ISSUE THREAD

**Issue by imilyukov** [Pierre-Lannoy/wp-opcache-manager#3]
https://github.com/Pierre-Lannoy/wp-opcache-manager/blob/80e1847afd7f045108bff129bcb49b556c3632e0/includes/system/class-opcache.php#L228

Hi everyone, the 3th argument is required for **sprintf**
I have got the error during warmup operation:

Fatal error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /var/www/html/web/wp-content/plugins/opcache-manager/includes/system/class-opcache.php on line 228

PHP version: 8.3.4

**Comment by Pierre-Lannoy** [comment]
Hello @imilyukov !
It will be fixed in the next release.
